language: python

git:
  depth: 1

jobs:
  fast_finish: true
  include:
  - name: Python 3.6 on Linux
    python: 3.6

install:
  - pip install -r requirements.txt

script:
  - coverage run --source=tests -m unittest discover tests

after_success:
  - pip install codecov
  - codecov
